language: python

python:
  - "2.7"

env:
  - DJANGO_SETTINGS_MODULE=agoracommuns.settings.test

# installing dependencies
install:
  pip install -r requirements/test.txt

# command to run tests
script: python agoracommuns/manage.py test
