language: python

python:
  - "2.7"

env:
  - DJANGO_SETTINGS_MODULE=agoracommuns.settings.test

cache:
  directories:
    - /home/travis/virtualenv/python2.7/lib/python2.7/site-packages
    - $HOME/.pip-cache/

# installing dependencies
install:
  pip install -r requirements/test.txt --download-cache $HOME/.pip-cache

# command to run tests
script: python agoracommuns/manage.py test core
